package ru.maltsev.primemarketbackend.money.domain;

public enum MoneyOperationEventType {
    DEPOSIT_CREATED,
    DEPOSIT_DETAILS_ISSUED,
    DEPOSIT_USER_MARKED_PAID,
    DEPOSIT_CONFIRMED,
    DEPOSIT_REJECTED,
    DEPOSIT_CANCELLED,
    WITHDRAWAL_CREATED,
    WITHDRAWAL_CANCELLED,
    WITHDRAWAL_TAKEN,
    WITHDRAWAL_REJECTED,
    WITHDRAWAL_CONFIRMED
}
