create type deposit_request_status as enum (
    'PENDING_DETAILS',
    'WAITING_PAYMENT',
    'PAYMENT_VERIFICATION',
    'CONFIRMED',
    'REJECTED',
    'EXPIRED',
    'CANCELLED'
    );

create table deposit_requests
(
    id                  bigint primary key generated by default as identity,
    public_id           uuid                   not null default gen_random_uuid(),
    user_id             bigint                 not null references users (id) on delete cascade,
    amount              numeric(13, 4)         not null check (amount > 0),
    deposit_method_id   bigint                 not null references deposit_methods (id),
    status              deposit_request_status not null default 'PENDING_DETAILS',
    payment_details     jsonb,

    created_at          timestamptz            not null default now(),
    updated_at          timestamptz            not null default now(),

    details_issued_at   timestamptz,

    user_marked_paid_at timestamptz,
    confirmed_at        timestamptz,

    rejected_at         timestamptz,
    reject_reason       text,

    cancelled_at        timestamptz
);

create unique index uq_deposit_requests_public_id on deposit_requests (public_id);
create index idx_deposit_requests_user_id on deposit_requests (user_id);

create trigger trg_deposit_requests_updated_at
    before update
    on deposit_requests
    for each row
execute function touch_updated_at();