create table games
(
    id         bigint primary key generated by default as identity,
    name       text    not null,
    slug       text    not null,
    logo_key   text    not null,
    is_active  boolean not null default true,
    sort_order integer not null default 0
);

create unique index uq_games_slug on games (slug);
create index idx_games_active_sort on games (is_active, sort_order);
