create table games
(
    id         bigint primary key generated by default as identity,
    slug       varchar(64)  not null,
    title      varchar(100) not null,
    sort_order int          not null default 0,
    is_active  boolean      not null default true,
    created_at timestamptz  not null default now(),

    constraint games_title_not_blank check (btrim(title) <> ''),
    constraint games_slug_not_blank check (btrim(slug) <> ''),
    constraint games_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create unique index if not exists ux_games_slug on games (lower(slug));