create table game_servers
(
    id         bigint primary key generated by default as identity,
    game_id    bigint not null references games(id),
    name       text   not null,
    slug       text   not null,
    is_active  boolean not null default true,
    sort_order integer not null default 0,

    constraint uq_game_servers unique (game_id, slug)
);

create index idx_game_servers_game_active_sort on game_servers (game_id, is_active, sort_order);