create table categories
(
    id         bigint primary key generated by default as identity,
    game_id    bigint       not null references games (id),
    slug       varchar(64)  not null, -- основной ключ для фронта (i18n)
    title      varchar(100) not null, -- fallback для фронта
    sort_order int          not null default 0,
    is_active  boolean      not null default true,
    created_at timestamptz  not null default now(),

    constraint categories_title_not_blank check (btrim(title) <> ''),
    constraint categories_slug_not_blank check (btrim(slug) <> ''),
    constraint categories_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create unique index if not exists ux_categories_game_slug
    on categories (game_id, lower(slug));

create index if not exists ix_categories_game_active_sort
    on categories (game_id, is_active, sort_order, title);