create table product_categories
(
    id    bigint primary key generated by default as identity,
    code  text not null,
    title text not null,

    constraint uq_product_categories_code unique (code)
);

create table game_categories
(
    game_id     bigint references games (id),
    category_id bigint references product_categories (id),
    is_active   boolean not null default true,
    sort_order  integer not null default 0,

    primary key (game_id, category_id)
);

create index idx_game_categories_on_game_active on game_categories (game_id, is_active, sort_order)