create table context_dimensions
(
    id         bigint primary key generated by default as identity,
    game_id    bigint       not null references games (id),
    slug       varchar(64)  not null,
    title      varchar(100) not null, -- fallback для фронта
    sort_order int          not null default 0,
    is_active  boolean      not null default true,
    created_at timestamptz  not null default now(),

    constraint context_dimensions_title_not_blank check (btrim(title) <> ''),
    constraint context_dimensions_slug_not_blank check (btrim(slug) <> ''),
    constraint context_dimensions_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create unique index if not exists ux_context_dimensions_game_slug
    on context_dimensions (game_id, lower(slug));

create index if not exists ix_context_dimensions_game_active_sort
    on context_dimensions (game_id, is_active, sort_order, title);