create table context_dimension_values
(
    id                   bigint primary key generated by default as identity,
    context_dimension_id bigint       not null references context_dimensions (id),
    slug                 varchar(64)  not null,
    title                varchar(100) not null, -- fallback для фронта
    sort_order           int          not null default 0,
    is_active            boolean      not null default true,
    created_at           timestamptz  not null default now(),

    constraint context_dimension_values_title_not_blank check (btrim(title) <> ''),
    constraint context_dimension_values_slug_not_blank check (btrim(slug) <> ''),
    constraint context_dimension_values_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create unique index if not exists ux_context_dimension_values_dimension_slug
    on context_dimension_values (context_dimension_id, lower(slug));

create index if not exists ix_context_dimension_values_dimension_active_sort
    on context_dimension_values (context_dimension_id, is_active, sort_order, title);