create table products
(
    id           bigint primary key generated by default as identity,
    game_id      bigint not null references games(id),
    category_id  bigint not null references product_categories(id),

    title        text not null,
    slug         text not null,         -- уникальный внутри игры
    is_active    boolean not null default true,
    sort_order  integer not null default 0,

    -- единица измерения: 'pcs', 'hours', 'm' (миллионы), 'gold', ...
    unit_code    text not null default 'pcs',

    metadata     jsonb not null default '{}'::jsonb,

    constraint uq_products_game_slug unique (game_id, slug)
);

create index idx_products_game_category_active on products (game_id, category_id, is_active, sort_order);