create table category_context_dimensions
(
    id                   bigint primary key generated by default as identity,
    category_id          bigint      not null references categories (id),
    context_dimension_id bigint      not null references context_dimensions (id),
    is_required          boolean     not null default true,
    sort_order           int         not null default 0,
    default_value_id     bigint      null references context_dimension_values (id),
    created_at           timestamptz not null default now(),

    constraint ux_category_context_dimensions unique (category_id, context_dimension_id)
);

create index if not exists ix_category_context_dimensions_category_sort
    on category_context_dimensions (category_id, sort_order, id);