create type offer_side as enum ('SELL', 'BUY');
create type offer_status as enum ('ACTIVE', 'PAUSED', 'CLOSED');

create table offers
(
    id            bigint primary key generated by default as identity,
    public_id     uuid           not null default gen_random_uuid(),

    user_id       bigint         not null references users (id),

    product_id    bigint         not null references products (id),
    server_id     bigint references game_servers (id),

    side          offer_side     not null,                              -- sell/buy

    currency_code varchar(5)     not null references currencies (code), -- валюта цены объявления
    unit_price    decimal(13, 4) not null,                              -- цена за 1 unit_code в currency_code

    quantity      bigint         not null,                              -- сколько всего продаёт/покупает
    min_quantity  bigint         not null default 1,                    -- минималка в одной сделке
    multiplicity  bigint         not null default 1,                    -- кратность

    status        offer_status   not null default 'ACTIVE',

    details       jsonb          not null default '{}'::jsonb,          -- например ник/персонаж, условия услуги и т.п.

    created_at    timestamptz    not null default now(),
    updated_at    timestamptz    not null default now(),

    constraint ck_offer_price_positive check (unit_price > 0),
    constraint ck_offer_min_qty check (min_quantity >= 1 and min_quantity <= quantity),
    constraint ck_offer_multiplicity check (multiplicity <= quantity)
);

create index idx_offers_search on offers (product_id, server_id, status, side);
create index idx_offers_user on offers (user_id, status);
create unique index uq_offers_public_id on offers (public_id);