create table fx_rates
(
    id         bigint primary key generated by default as identity,
    base_code  varchar(5)     not null references currencies (code),
    quote_code varchar(5)     not null references currencies (code),
    rate       numeric(18, 8) not null, -- 1 base = rate quote
    valid_to   timestamptz    not null, -- когда курс актуален
    provider   text           not null, -- 'ecb', 'binance', 'manual' и т.п.
    created_at timestamptz    not null default now(),

    constraint ck_fx_rate_positive check (rate > 0),
    constraint ck_fx_pair_not_same check (base_code <> quote_code)
);

create index idx_fx_rates_pair_valid_to on fx_rates (base_code, quote_code, valid_to desc);