create table category_attributes
(
    id           bigint primary key generated by default as identity,
    category_id  bigint       not null references categories (id),
    slug         varchar(64)  not null,
    title        varchar(100) not null, -- fallback для фронта
    data_type    varchar(32)  not null,
    is_required  boolean      not null default false,
    sort_order   int          not null default 0,
    is_active    boolean      not null default true,
    created_at   timestamptz  not null default now(),

    constraint category_attributes_title_not_blank check (btrim(title) <> ''),
    constraint category_attributes_slug_not_blank check (btrim(slug) <> ''),
    constraint category_attributes_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint category_attributes_data_type_check
        check (data_type in ('select', 'multiselect', 'text', 'number', 'boolean'))
);

create unique index if not exists ux_category_attributes_category_slug
    on category_attributes (category_id, lower(slug));

create index if not exists ix_category_attributes_category_active_sort
    on category_attributes (category_id, is_active, sort_order, title);