create table users
(
    id            bigint primary key generated by default as identity,
    username      varchar(24)  not null,
    email         varchar(254) not null,
    password_hash varchar(255) not null,
    is_active     boolean      not null default true,

    created_at    timestamptz  not null default now(),

    constraint username_length check (char_length(username) >= 3)
);

create unique index if not exists ux_users_email on users (lower(email));
create unique index if not exists ux_users_username on users (lower(username));