create type order_status as enum
    (
        'created',            -- создали ордер
        'funds_reserved',     -- деньги покупателя зарезервированы
        'in_progress',        -- ожидаем выполнение (передача предмета/услуги)
        'completed',          -- успешно
        'cancelled',          -- отменён до выполнения
        'disputed',           -- спор
        'refunded'            -- возврат
        );

create table orders
(
    id                  bigint primary key generated by default as identity,
    public_id           uuid not null default gen_random_uuid(),

    offer_id            bigint not null references offers(id),

    buyer_id            bigint not null references users(id), -- todo: public_id?
    seller_id           bigint not null references users(id),

    quantity            bigint not null,

    -- валюта/цена продавца (та же, что в offer)
    seller_currency_code varchar(5) not null references currencies(code),
    unit_price_seller    decimal(13,4) not null,

    -- валюта, в которой платит покупатель (валюта его кошелька, которую он выбрал)
    buyer_currency_code  varchar(5) not null references currencies(code),

    -- FX lock: курс и время фиксации (храним прямо в ордере — надёжно и просто)
    fx_rate              numeric(18,8) not null,   -- 1 seller_currency = fx_rate buyer_currency (или наоборот, но строго один стандарт)

    -- суммы:
    amount_seller        decimal(13,4) not null,   -- quantity * unit_price_seller
    amount_buyer         decimal(13,4) not null,   -- amount_seller * fx_rate (по вашей формуле)

    status              order_status not null default 'created',

    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),

    constraint ck_order_qty_pos check (quantity > 0),
    constraint ck_order_amounts_pos check (amount_seller > 0 and amount_buyer > 0),
    constraint ck_order_rate_pos check (fx_rate > 0)
);

create unique index uq_orders_public_id on orders (public_id);
create index idx_orders_buyer_status on orders (buyer_id, status, created_at desc);
create index idx_orders_seller_status on orders (seller_id, status, created_at desc);