create table category_attribute_options
(
    id                    bigint primary key generated by default as identity,
    category_attribute_id bigint       not null references category_attributes (id),
    slug                  varchar(64)  not null,
    title                 varchar(100) not null, -- fallback для фронта
    sort_order            int          not null default 0,
    is_active             boolean      not null default true,
    created_at            timestamptz  not null default now(),

    constraint category_attribute_options_title_not_blank check (btrim(title) <> ''),
    constraint category_attribute_options_slug_not_blank check (btrim(slug) <> ''),
    constraint category_attribute_options_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create unique index if not exists ux_category_attribute_options_attribute_slug
    on category_attribute_options (category_attribute_id, lower(slug));

create index if not exists ix_category_attribute_options_attribute_active_sort
    on category_attribute_options (category_attribute_id, is_active, sort_order, title);