create table offers
(
    id                  bigint primary key generated by default as identity,
    user_id             bigint        not null references users (id),
    game_id             bigint        not null references games (id),
    category_id         bigint        not null references categories (id),

    side                varchar(8)    not null,
    title               varchar(200)  null,
    description         text          null,
    trade_terms         text          null,

    price_currency_code varchar(5)    null references currencies (code),
    price_amount        numeric(18,8) null,

    quantity            numeric(18,8) null,
    min_trade_quantity  numeric(18,8) null,
    max_trade_quantity  numeric(18,8) null,
    quantity_step       numeric(18,8) null,

    status              varchar(16)   not null default 'draft',
    created_at          timestamptz   not null default now(),
    updated_at          timestamptz   not null default now(),
    published_at        timestamptz   null,

    constraint offers_side_check
        check (side in ('buy', 'sell')),

    constraint offers_status_check
        check (status in ('draft', 'active', 'paused', 'closed', 'deleted')),

    constraint offers_title_not_blank
        check (title is null or btrim(title) <> ''),

    constraint offers_price_amount_positive
        check (price_amount is null or price_amount > 0),

    constraint offers_quantity_positive
        check (quantity is null or quantity > 0),

    constraint offers_min_trade_quantity_positive
        check (min_trade_quantity is null or min_trade_quantity > 0),

    constraint offers_max_trade_quantity_positive
        check (max_trade_quantity is null or max_trade_quantity > 0),

    constraint offers_quantity_step_positive
        check (quantity_step is null or quantity_step > 0),

    constraint offers_min_lte_max
        check (
            min_trade_quantity is null
                or max_trade_quantity is null
                or min_trade_quantity <= max_trade_quantity
            ),

    constraint offers_max_lte_quantity
        check (
            max_trade_quantity is null
                or quantity is null
                or max_trade_quantity <= quantity
            )
);

create index if not exists ix_offers_user_id
    on offers (user_id);

create index if not exists ix_offers_game_category_side_status
    on offers (game_id, category_id, side, status);

create index if not exists ix_offers_status_published_at
    on offers (status, published_at desc);

create trigger trg_offers_touch_updated_at
    before update on offers
    for each row
execute function touch_updated_at();