create table offer_context_values
(
    id                         bigint primary key generated by default as identity,
    offer_id                   bigint      not null references offers (id) on delete cascade,
    context_dimension_id       bigint      not null references context_dimensions (id),
    context_dimension_value_id bigint      not null references context_dimension_values (id),
    created_at                 timestamptz not null default now(),

    constraint ux_offer_context_values_offer_dimension
        unique (offer_id, context_dimension_id)
);

create index if not exists ix_offer_context_values_offer_id
    on offer_context_values (offer_id);

create index if not exists ix_offer_context_values_dimension_value
    on offer_context_values (context_dimension_id, context_dimension_value_id);