create table offer_attribute_values
(
    id                           bigint primary key generated by default as identity,
    offer_id                     bigint      not null references offers (id) on delete cascade,
    category_attribute_id        bigint      not null references category_attributes (id),
    category_attribute_option_id bigint      null references category_attribute_options (id),

    value_text                   text        null,
    value_number                 numeric(18,8) null,
    value_boolean                boolean     null,

    created_at                   timestamptz not null default now(),

    constraint ux_offer_attribute_values_offer_attribute
        unique (offer_id, category_attribute_id),

    constraint offer_attribute_values_some_value_check
        check (
            category_attribute_option_id is not null
                or value_text is not null
                or value_number is not null
                or value_boolean is not null
            )
);

create index if not exists ix_offer_attribute_values_offer_id
    on offer_attribute_values (offer_id);

create index if not exists ix_offer_attribute_values_attribute_id
    on offer_attribute_values (category_attribute_id);

create index if not exists ix_offer_attribute_values_option_id
    on offer_attribute_values (category_attribute_option_id);