create table delivery_methods
(
    id          bigint primary key generated by default as identity,
    category_id bigint       not null references categories (id),
    slug        varchar(64)  not null,
    title       varchar(100) not null, -- fallback для фронта
    sort_order  int          not null default 0,
    is_active   boolean      not null default true,
    created_at  timestamptz  not null default now(),

    constraint delivery_methods_title_not_blank check (btrim(title) <> ''),
    constraint delivery_methods_slug_not_blank check (btrim(slug) <> ''),
    constraint delivery_methods_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create unique index if not exists ux_delivery_methods_category_slug
    on delivery_methods (category_id, lower(slug));

create index if not exists ix_delivery_methods_category_active_sort
    on delivery_methods (category_id, is_active, sort_order, title);