create table category_trade_field_configs
(
    id                   bigint primary key generated by default as identity,
    category_id          bigint       not null references categories (id),
    field_slug           varchar(64)  not null,
    is_visible           boolean      not null default true,
    is_required          boolean      not null default false,
    is_multiselect       boolean      not null default false,
    default_value_text   varchar(255) null,
    default_value_number numeric(18,8) null,
    sort_order           int          not null default 0,
    created_at           timestamptz  not null default now(),

    constraint category_trade_field_configs_field_slug_not_blank
        check (btrim(field_slug) <> ''),

    constraint category_trade_field_configs_field_slug_format
        check (field_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),

    constraint ux_category_trade_field_configs_category_field
        unique (category_id, field_slug)
);

create index if not exists ix_category_trade_field_configs_category_sort
    on category_trade_field_configs (category_id, sort_order, id);