create table currency_rates
(
    id                 bigint primary key generated by default as identity,
    from_currency_code varchar(5)   not null references currencies (code),
    to_currency_code   varchar(5)   not null references currencies (code),
    rate               decimal(20,8) not null,

    source             varchar(32)  not null, -- manual / scheduler / system
    note               text         null,

    created_at         timestamptz  not null default now(),
    updated_at         timestamptz  not null default now(),

    constraint ck_currency_rates_rate_positive
        check (rate > 0),

    constraint ck_currency_rates_different_currencies
        check (from_currency_code <> to_currency_code),

    constraint ck_currency_rates_source
        check (source in ('manual', 'scheduler', 'system')),

    constraint uq_currency_rates_pair
        unique (from_currency_code, to_currency_code)
);

create index if not exists ix_currency_rates_from_to
    on currency_rates (from_currency_code, to_currency_code);

create trigger trg_currency_rates_touch_updated_at
    before update on currency_rates
    for each row
execute function touch_updated_at();