create table if not exists refresh_tokens
(
    id          bigint primary key generated by default as identity,
    user_id     bigint      not null,
    token_hash  varchar(64) not null,
    expires_at  timestamptz not null,
    revoked_at  timestamptz,

    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),

    constraint fk_refresh_tokens_user foreign key (user_id) references users (id) on delete cascade
);

create unique index if not exists ux_refresh_tokens_token_hash on refresh_tokens (token_hash);
create index if not exists ix_refresh_tokens_user_id on refresh_tokens (user_id);
