create table order_quotes
(
    id                                 bigint primary key generated by default as identity,
    public_id                          uuid          not null,
    offer_id                           bigint        not null references offers (id) on delete cascade,
    offer_version_snapshot             bigint        not null,
    intent                             varchar(8)    not null,
    viewer_currency_code               varchar(5)    not null references currencies (code),
    offer_side_snapshot                varchar(8)    not null,
    owner_user_id                      bigint        not null references users (id),
    owner_username_snapshot            varchar(24)   not null,
    game_id_snapshot                   bigint        not null,
    game_slug_snapshot                 varchar(64)   not null,
    game_title_snapshot                varchar(100)  not null,
    category_id_snapshot               bigint        not null,
    category_slug_snapshot             varchar(64)   not null,
    category_title_snapshot            varchar(100)  not null,
    title_snapshot                     varchar(200)  null,
    description_snapshot               text          null,
    trade_terms_snapshot               text          null,
    published_at_snapshot              timestamptz   not null,
    quantity_snapshot                  numeric(18,8) not null,
    min_trade_quantity_snapshot        numeric(18,8) null,
    max_trade_quantity_snapshot        numeric(18,8) null,
    quantity_step_snapshot             numeric(18,8) null,
    offer_price_currency_code_snapshot varchar(5)    not null references currencies (code),
    offer_price_amount_snapshot        numeric(18,8) not null,
    fx_from_currency_code              varchar(5)    not null references currencies (code),
    fx_to_currency_code                varchar(5)    not null references currencies (code),
    fx_rate                            numeric(20,8) not null,
    display_unit_price_amount          numeric(20,8) not null,
    contexts_snapshot                  jsonb         not null default '[]'::jsonb,
    attributes_snapshot                jsonb         not null default '[]'::jsonb,
    delivery_methods_snapshot          jsonb         not null default '[]'::jsonb,
    status                             varchar(16)   not null default 'active',
    expires_at                         timestamptz   not null,
    created_at                         timestamptz   not null default now(),
    updated_at                         timestamptz   not null default now(),

    constraint ux_order_quotes_public_id
        unique (public_id),

    constraint order_quotes_offer_version_positive
        check (offer_version_snapshot > 0),

    constraint order_quotes_intent_check
        check (intent in ('buy', 'sell')),

    constraint order_quotes_offer_side_check
        check (offer_side_snapshot in ('buy', 'sell')),

    constraint order_quotes_status_check
        check (status in ('active', 'expired', 'consumed', 'invalidated')),

    constraint order_quotes_intent_side_match
        check (
            (intent = 'buy' and offer_side_snapshot = 'sell')
                or (intent = 'sell' and offer_side_snapshot = 'buy')
            ),

    constraint order_quotes_quantity_positive
        check (quantity_snapshot > 0),

    constraint order_quotes_min_trade_quantity_positive
        check (min_trade_quantity_snapshot is null or min_trade_quantity_snapshot > 0),

    constraint order_quotes_max_trade_quantity_positive
        check (max_trade_quantity_snapshot is null or max_trade_quantity_snapshot > 0),

    constraint order_quotes_quantity_step_positive
        check (quantity_step_snapshot is null or quantity_step_snapshot > 0),

    constraint order_quotes_offer_price_positive
        check (offer_price_amount_snapshot > 0),

    constraint order_quotes_fx_rate_positive
        check (fx_rate > 0),

    constraint order_quotes_display_unit_price_positive
        check (display_unit_price_amount > 0),

    constraint order_quotes_contexts_snapshot_array
        check (jsonb_typeof(contexts_snapshot) = 'array'),

    constraint order_quotes_attributes_snapshot_array
        check (jsonb_typeof(attributes_snapshot) = 'array'),

    constraint order_quotes_delivery_methods_snapshot_array
        check (jsonb_typeof(delivery_methods_snapshot) = 'array')
);

create index if not exists ix_order_quotes_offer_id_created_at
    on order_quotes (offer_id, created_at desc);

create index if not exists ix_order_quotes_status_expires_at
    on order_quotes (status, expires_at);

create index if not exists ix_order_quotes_owner_user_id_created_at
    on order_quotes (owner_user_id, created_at desc);

create trigger trg_order_quotes_touch_updated_at
    before update on order_quotes
    for each row
execute function touch_updated_at();
