create table orders
(
    id                                 bigint primary key generated by default as identity,
    public_id                          uuid           not null,
    order_quote_id                     bigint         not null references order_quotes (id),
    maker_user_id                      bigint         not null references users (id),
    taker_user_id                      bigint         not null references users (id),
    maker_role                         varchar(8)     not null,
    taker_role                         varchar(8)     not null,
    game_id_snapshot                   bigint         not null,
    game_slug_snapshot                 varchar(64)    not null,
    game_title_snapshot                varchar(100)   not null,
    category_id_snapshot               bigint         not null,
    category_slug_snapshot             varchar(64)    not null,
    category_title_snapshot            varchar(100)   not null,
    offer_side_snapshot                varchar(8)     not null,
    intent_snapshot                    varchar(8)     not null,
    owner_username_snapshot            varchar(24)    not null,
    title_snapshot                     varchar(200)   null,
    description_snapshot               text           null,
    trade_terms_snapshot               text           null,
    ordered_quantity                   numeric(18, 8) not null,
    delivered_quantity                 numeric(18, 8) not null default 0,
    offer_price_currency_code_snapshot varchar(5)     not null references currencies (code),
    offer_price_amount_snapshot        numeric(18, 8) not null,
    viewer_currency_code_snapshot      varchar(5)     not null references currencies (code),
    fx_from_currency_code              varchar(5)     not null references currencies (code),
    fx_to_currency_code                varchar(5)     not null references currencies (code),
    fx_rate                            numeric(20, 8) not null,
    display_unit_price_amount          numeric(20, 8) not null,
    display_total_amount               numeric(20, 8) not null,
    seller_gross_amount                numeric(20, 8) not null,
    seller_fee_bps_snapshot            integer        not null,
    seller_fee_amount                  numeric(20, 8) not null,
    seller_net_amount                  numeric(20, 8) not null,
    contexts_snapshot                  jsonb          not null default '[]'::jsonb,
    attributes_snapshot                jsonb          not null default '[]'::jsonb,
    delivery_methods_snapshot          jsonb          not null default '[]'::jsonb,
    cancel_requested_by_role           varchar(8)     null,
    cancel_requested_at                timestamptz    null,
    status                             varchar(32)    not null default 'pending',
    expires_at                         timestamptz    not null,
    created_at                         timestamptz    not null default now(),
    updated_at                         timestamptz    not null default now(),

    constraint ux_orders_public_id
        unique (public_id),

    constraint ux_orders_order_quote_id
        unique (order_quote_id),

    constraint orders_maker_taker_different
        check (maker_user_id <> taker_user_id),

    constraint orders_maker_role_check
        check (maker_role in ('buyer', 'seller')),

    constraint orders_taker_role_check
        check (taker_role in ('buyer', 'seller')),

    constraint orders_counterparty_roles_check
        check (
            (maker_role = 'buyer' and taker_role = 'seller')
                or (maker_role = 'seller' and taker_role = 'buyer')
            ),

    constraint orders_offer_side_check
        check (offer_side_snapshot in ('buy', 'sell')),

    constraint orders_intent_check
        check (intent_snapshot in ('buy', 'sell')),

    constraint orders_status_check
        check (status in ('pending', 'in_progress', 'partially_delivered', 'delivered', 'completed', 'canceled', 'expired')),

    constraint orders_cancel_requested_role_check
        check (cancel_requested_by_role is null or cancel_requested_by_role in ('buyer', 'seller')),

    constraint orders_cancel_request_fields_check
        check (
            (cancel_requested_by_role is null and cancel_requested_at is null)
                or (cancel_requested_by_role is not null and cancel_requested_at is not null)
            ),

    constraint orders_ordered_quantity_positive
        check (ordered_quantity > 0),

    constraint orders_delivered_quantity_nonnegative
        check (delivered_quantity >= 0),

    constraint orders_delivered_quantity_lte_ordered
        check (delivered_quantity <= ordered_quantity),

    constraint orders_offer_price_positive
        check (offer_price_amount_snapshot > 0),

    constraint orders_fx_rate_positive
        check (fx_rate > 0),

    constraint orders_display_unit_price_positive
        check (display_unit_price_amount > 0),

    constraint orders_display_total_positive
        check (display_total_amount > 0),

    constraint orders_seller_gross_positive
        check (seller_gross_amount > 0),

    constraint orders_seller_fee_bps_range
        check (seller_fee_bps_snapshot >= 0 and seller_fee_bps_snapshot <= 10000),

    constraint orders_seller_fee_amount_nonnegative
        check (seller_fee_amount >= 0),

    constraint orders_seller_net_amount_nonnegative
        check (seller_net_amount >= 0),

    constraint orders_contexts_snapshot_array
        check (jsonb_typeof(contexts_snapshot) = 'array'),

    constraint orders_attributes_snapshot_array
        check (jsonb_typeof(attributes_snapshot) = 'array'),

    constraint orders_delivery_methods_snapshot_array
        check (jsonb_typeof(delivery_methods_snapshot) = 'array')
);

create index if not exists ix_orders_maker_user_id_created_at
    on orders (maker_user_id, created_at desc);

create index if not exists ix_orders_taker_user_id_created_at
    on orders (taker_user_id, created_at desc);

create index if not exists ix_orders_status_expires_at
    on orders (status, expires_at);

create trigger trg_orders_touch_updated_at
    before update on orders
    for each row
execute function touch_updated_at();

create table offer_reservations
(
    id          bigint primary key generated by default as identity,
    order_id    bigint         not null references orders (id),
    offer_id    bigint         not null references offers (id),
    quantity    numeric(18, 8) not null,
    status      varchar(16)    not null default 'active',
    expires_at  timestamptz    not null,
    created_at  timestamptz    not null default now(),
    updated_at  timestamptz    not null default now(),
    released_at timestamptz    null,
    consumed_at timestamptz    null,

    constraint ux_offer_reservations_order_id
        unique (order_id),

    constraint offer_reservations_quantity_positive
        check (quantity > 0),

    constraint offer_reservations_status_check
        check (status in ('active', 'released', 'consumed', 'expired'))
);

create index if not exists ix_offer_reservations_offer_id_status
    on offer_reservations (offer_id, status);

create index if not exists ix_offer_reservations_status_expires_at
    on offer_reservations (status, expires_at);

create trigger trg_offer_reservations_touch_updated_at
    before update on offer_reservations
    for each row
execute function touch_updated_at();

create table user_account_holds
(
    id              bigint primary key generated by default as identity,
    public_id       uuid           not null,
    order_id        bigint         not null references orders (id),
    user_account_id bigint         not null references user_accounts (id),
    amount          decimal(13, 4) not null,
    status          varchar(16)    not null default 'active',
    reason          varchar(32)    not null,
    expires_at      timestamptz    not null,
    created_at      timestamptz    not null default now(),
    updated_at      timestamptz    not null default now(),
    released_at     timestamptz    null,
    consumed_at     timestamptz    null,

    constraint ux_user_account_holds_public_id
        unique (public_id),

    constraint ux_user_account_holds_order_reason
        unique (order_id, reason),

    constraint user_account_holds_amount_positive
        check (amount > 0),

    constraint user_account_holds_status_check
        check (status in ('active', 'released', 'consumed', 'expired')),

    constraint user_account_holds_reason_check
        check (reason in ('order_funds_hold'))
);

create index if not exists ix_user_account_holds_user_account_id_status
    on user_account_holds (user_account_id, status);

create index if not exists ix_user_account_holds_status_expires_at
    on user_account_holds (status, expires_at);

create trigger trg_user_account_holds_touch_updated_at
    before update on user_account_holds
    for each row
execute function touch_updated_at();
