alter table user_account_holds
    add column ref_type varchar(16),
    add column ref_id bigint;

update user_account_holds
set ref_type = 'order',
    ref_id = order_id
where ref_type is null;

alter table user_account_holds
    alter column ref_type set not null,
    alter column ref_id set not null,
    alter column expires_at drop not null;

alter table user_account_holds
    drop constraint ux_user_account_holds_order_reason;

alter table user_account_holds
    drop constraint user_account_holds_reason_check;

alter table user_account_holds
    add constraint user_account_holds_ref_type_check
        check (ref_type in ('offer', 'order')),
    add constraint user_account_holds_reason_check
        check (reason in ('buy_offer_funds_hold', 'order_funds_hold')),
    add constraint user_account_holds_reason_ref_check
        check (
            (reason = 'buy_offer_funds_hold' and ref_type = 'offer')
                or (reason = 'order_funds_hold' and ref_type = 'order')
            ),
    add constraint user_account_holds_expiry_check
        check (
            (ref_type = 'offer' and expires_at is null)
                or (ref_type = 'order' and expires_at is not null)
            );

create unique index if not exists ux_user_account_holds_ref_reason
    on user_account_holds (ref_type, ref_id, reason);

create index if not exists ix_user_account_holds_ref_status
    on user_account_holds (ref_type, ref_id, status);

alter table user_account_holds
    drop column order_id;

create table user_account_hold_allocations
(
    id                   bigint primary key generated by default as identity,
    user_account_hold_id bigint         not null references user_account_holds (id),
    order_id             bigint         not null references orders (id),
    amount               decimal(13, 4) not null,
    status               varchar(16)    not null default 'active',
    expires_at           timestamptz    not null,
    created_at           timestamptz    not null default now(),
    updated_at           timestamptz    not null default now(),
    released_at          timestamptz    null,
    consumed_at          timestamptz    null,

    constraint ux_user_account_hold_allocations_order_id
        unique (order_id),

    constraint user_account_hold_allocations_amount_positive
        check (amount > 0),

    constraint user_account_hold_allocations_status_check
        check (status in ('active', 'released', 'consumed', 'expired'))
);

create index if not exists ix_user_account_hold_allocations_hold_id_status
    on user_account_hold_allocations (user_account_hold_id, status);

create index if not exists ix_user_account_hold_allocations_status_expires_at
    on user_account_hold_allocations (status, expires_at);

create trigger trg_user_account_hold_allocations_touch_updated_at
    before update on user_account_hold_allocations
    for each row
execute function touch_updated_at();
