create table order_events
(
    id            bigint primary key generated by default as identity,
    order_id      bigint      not null references orders (id),
    event_type    varchar(64) not null,
    actor_user_id bigint      null references users (id),
    actor_role    varchar(8)  null,
    payload       jsonb       not null default '{}'::jsonb,
    created_at    timestamptz not null default now(),

    constraint order_events_event_type_check
        check (
            event_type in (
                'order_created',
                'maker_confirmed_ready',
                'order_canceled',
                'order_expired',
                'seller_marked_partial_delivery',
                'seller_marked_delivered',
                'buyer_confirmed_received',
                'change_requested',
                'change_approved',
                'change_rejected'
            )
        ),

    constraint order_events_actor_role_check
        check (
            actor_role is null
                or actor_role in ('buyer', 'seller', 'system')
            ),

    constraint order_events_actor_fields_check
        check (
            (actor_role is null and actor_user_id is null)
                or (actor_role in ('buyer', 'seller') and actor_user_id is not null)
                or (actor_role = 'system' and actor_user_id is null)
            ),

    constraint order_events_payload_object
        check (jsonb_typeof(payload) = 'object')
);

create index if not exists ix_order_events_order_id_created_at_id
    on order_events (order_id, created_at asc, id asc);

create or replace function fn_order_events_block_mutation()
    returns trigger
    language plpgsql
as $$
begin
    if tg_op = 'UPDATE' then
        raise exception 'Updating rows in order_events is not allowed';
    end if;

    if tg_op = 'DELETE' then
        raise exception 'Deleting rows from order_events is not allowed';
    end if;

    return null;
end;
$$;

create trigger trg_order_events_block_update
    before update on order_events
    for each row
execute function fn_order_events_block_mutation();

create trigger trg_order_events_block_delete
    before delete on order_events
    for each row
execute function fn_order_events_block_mutation();
