create table platform_accounts
(
    id            bigint primary key generated by default as identity,
    currency_code varchar(5)     not null references currencies (code),
    balance       decimal(13, 4) not null default 0,
    reserved      decimal(13, 4) not null default 0,

    constraint uq_platform_accounts_currency_code
        unique (currency_code),

    constraint ck_platform_accounts_balance_nonnegative
        check (balance >= 0),

    constraint ck_platform_accounts_reserved_nonnegative
        check (reserved >= 0),

    constraint ck_platform_accounts_balance_ge_reserved
        check (balance >= reserved)
);

create extension if not exists pgcrypto;

create table platform_account_txs
(
    id                  bigint primary key generated by default as identity,
    public_id           uuid           not null default gen_random_uuid(),
    platform_account_id bigint         not null references platform_accounts (id),
    amount              decimal(13, 4) not null,
    type                text           not null,
    ref_type            text           not null,
    ref_id              bigint         not null,
    created_at          timestamptz    not null default now()
);

create unique index if not exists ux_platform_account_txs_public_id
    on platform_account_txs (public_id);

create unique index if not exists ux_platform_account_txs_ref
    on platform_account_txs (ref_type, ref_id);

create or replace function fn_platform_account_txs_apply_balance()
    returns trigger
    language plpgsql
as $$
begin
    update platform_accounts
    set balance = balance + new.amount
    where id = new.platform_account_id;

    return new;
end;
$$;

create trigger trg_platform_account_txs_apply_balance
    after insert on platform_account_txs
    for each row
execute function fn_platform_account_txs_apply_balance();

create or replace function fn_platform_account_txs_block_mutation()
    returns trigger
    language plpgsql
as $$
begin
    if tg_op = 'UPDATE' then
        if new.id <> old.id
            or new.public_id <> old.public_id
            or new.platform_account_id <> old.platform_account_id
            or new.amount <> old.amount then
            raise exception 'Updating id, public_id, platform_account_id, or amount is not allowed for platform_account_txs';
        end if;

        return new;
    end if;

    if tg_op = 'DELETE' then
        raise exception 'Deleting rows from platform_account_txs is not allowed';
    end if;

    return null;
end;
$$;

create trigger trg_platform_account_txs_block_update
    before update on platform_account_txs
    for each row
execute function fn_platform_account_txs_block_mutation();

create trigger trg_platform_account_txs_block_delete
    before delete on platform_account_txs
    for each row
execute function fn_platform_account_txs_block_mutation();

alter table order_events
    drop constraint order_events_event_type_check;

alter table order_events
    add constraint order_events_event_type_check
        check (
            event_type in (
                'order_created',
                'maker_confirmed_ready',
                'order_canceled',
                'order_expired',
                'seller_marked_partial_delivery',
                'seller_marked_delivered',
                'buyer_confirmed_received',
                'order_completed',
                'change_requested',
                'change_approved',
                'change_rejected'
            )
        );

alter table offers
    drop constraint offers_quantity_positive;

alter table offers
    add constraint offers_quantity_nonnegative
        check (quantity is null or quantity >= 0);
