create table order_requests
(
    id                    bigint primary key generated by default as identity,
    public_id             uuid           not null default gen_random_uuid(),
    order_id              bigint         not null references orders (id),
    request_type          varchar(32)    not null,
    requested_by_user_id  bigint         not null references users (id),
    requested_by_role     varchar(8)     not null,
    status                varchar(16)    not null default 'pending',
    reason                text           null,
    requested_quantity    numeric(18, 8) null,
    created_at            timestamptz    not null default now(),
    updated_at            timestamptz    not null default now(),
    resolved_at           timestamptz    null,
    resolved_by_user_id   bigint         null references users (id),

    constraint ux_order_requests_public_id
        unique (public_id),

    constraint order_requests_type_check
        check (request_type in ('cancel', 'amend_quantity')),

    constraint order_requests_status_check
        check (status in ('pending', 'approved', 'rejected', 'canceled', 'expired')),

    constraint order_requests_requested_by_role_check
        check (requested_by_role in ('buyer', 'seller')),

    constraint order_requests_reason_not_blank
        check (reason is null or btrim(reason) <> ''),

    constraint order_requests_requested_quantity_positive
        check (requested_quantity is null or requested_quantity > 0),

    constraint order_requests_type_quantity_check
        check (
            (request_type = 'cancel' and requested_quantity is null)
                or (request_type = 'amend_quantity' and requested_quantity is not null)
            ),

    constraint order_requests_resolution_fields_check
        check (
            (status = 'pending' and resolved_at is null and resolved_by_user_id is null)
                or (status <> 'pending' and resolved_at is not null and resolved_by_user_id is not null)
            )
);

create index if not exists ix_order_requests_order_id_status
    on order_requests (order_id, status, created_at desc);

create index if not exists ix_order_requests_requested_by_user_id_created_at
    on order_requests (requested_by_user_id, created_at desc);

create unique index if not exists ux_order_requests_order_type_pending
    on order_requests (order_id, request_type)
    where status = 'pending';

create trigger trg_order_requests_touch_updated_at
    before update on order_requests
    for each row
execute function touch_updated_at();

alter table offers
    drop constraint if exists offers_max_lte_quantity;

alter table order_events
    drop constraint order_events_event_type_check;

alter table order_events
    add constraint order_events_event_type_check
        check (
            event_type in (
                'order_created',
                'maker_confirmed_ready',
                'order_canceled',
                'order_expired',
                'seller_marked_partial_delivery',
                'seller_marked_delivered',
                'buyer_confirmed_received',
                'order_completed',
                'change_requested',
                'change_approved',
                'change_rejected',
                'cancel_requested',
                'cancel_request_approved',
                'cancel_request_rejected',
                'amend_quantity_requested',
                'amend_quantity_approved',
                'amend_quantity_rejected'
            )
        );
