create table order_conversations
(
    id                bigint primary key generated by default as identity,
    public_id         uuid        not null,
    order_id          bigint      not null references orders (id),
    conversation_type varchar(32) not null,
    status            varchar(16) not null default 'active',
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now(),
    last_message_at   timestamptz null,

    constraint ux_order_conversations_public_id
        unique (public_id),

    constraint ux_order_conversations_order_type
        unique (order_id, conversation_type),

    constraint order_conversations_type_check
        check (conversation_type in ('order_main', 'order_support_buyer', 'order_support_seller')),

    constraint order_conversations_status_check
        check (status in ('active', 'closed', 'archived'))
);

create index if not exists ix_order_conversations_order_id
    on order_conversations (order_id);

create index if not exists ix_order_conversations_last_message_at
    on order_conversations (last_message_at desc nulls last);

create trigger trg_order_conversations_touch_updated_at
    before update on order_conversations
    for each row
execute function touch_updated_at();

create table order_conversation_participants
(
    id               bigint primary key generated by default as identity,
    conversation_id  bigint      not null references order_conversations (id),
    user_id          bigint      not null references users (id),
    participant_role varchar(16) not null,
    joined_at        timestamptz not null default now(),

    constraint ux_order_conversation_participants_conversation_user
        unique (conversation_id, user_id),

    constraint order_conversation_participants_role_check
        check (participant_role in ('buyer', 'seller', 'support'))
);

create index if not exists ix_order_conversation_participants_user_id
    on order_conversation_participants (user_id);

create table order_messages
(
    id              bigint primary key generated by default as identity,
    public_id       uuid        not null,
    conversation_id bigint      not null references order_conversations (id),
    sender_user_id  bigint      null references users (id),
    message_type    varchar(16) not null,
    body            text        not null,
    created_at      timestamptz not null default now(),
    edited_at       timestamptz null,
    deleted_at      timestamptz null,

    constraint ux_order_messages_public_id
        unique (public_id),

    constraint order_messages_type_check
        check (message_type in ('text', 'system')),

    constraint order_messages_sender_check
        check (
            (message_type = 'system' and sender_user_id is null)
                or (message_type = 'text' and sender_user_id is not null)
        ),

    constraint order_messages_body_length_check
        check (char_length(body) > 0 and char_length(body) <= 4000)
);

create index if not exists ix_order_messages_conversation_created_at_id
    on order_messages (conversation_id, created_at desc, id desc);
