create table order_disputes
(
    id                       bigint primary key generated by default as identity,
    public_id                uuid         not null,
    order_id                 bigint       not null references orders (id),
    opened_by_user_id        bigint       not null references users (id),
    opened_by_role           varchar(16)  not null,
    status                   varchar(16)  not null default 'open',
    reason_code              varchar(64)  not null,
    description              text         not null,
    assigned_support_user_id bigint       null references users (id),
    taken_at                 timestamptz  null,
    created_at               timestamptz  not null default now(),
    updated_at               timestamptz  not null default now(),
    resolved_at              timestamptz  null,
    resolved_by_user_id      bigint       null references users (id),
    resolution_type          varchar(64)  null,
    resolution_note          text         null,

    constraint ux_order_disputes_public_id
        unique (public_id),

    constraint order_disputes_opened_by_role_check
        check (opened_by_role in ('buyer', 'seller', 'support')),

    constraint order_disputes_status_check
        check (status in ('open', 'in_review', 'resolved', 'closed')),

    constraint order_disputes_reason_code_not_blank
        check (btrim(reason_code) <> ''),

    constraint order_disputes_description_not_blank
        check (btrim(description) <> ''),

    constraint order_disputes_resolution_type_check
        check (
            resolution_type is null
                or resolution_type in (
                    'force_cancel',
                    'force_complete',
                    'force_amend_quantity_and_complete'
                )
        ),

    constraint order_disputes_resolution_note_not_blank
        check (resolution_note is null or btrim(resolution_note) <> ''),

    constraint order_disputes_taken_assignment_check
        check (
            (assigned_support_user_id is null and taken_at is null)
                or (assigned_support_user_id is not null and taken_at is not null)
        ),

    constraint order_disputes_resolution_fields_check
        check (
            (status in ('open', 'in_review')
                and resolved_at is null
                and resolved_by_user_id is null
                and resolution_type is null
                and resolution_note is null)
                or
            (status in ('resolved', 'closed')
                and resolved_at is not null
                and resolved_by_user_id is not null
                and resolution_type is not null)
        )
);

create index if not exists ix_order_disputes_order_id
    on order_disputes (order_id);

create index if not exists ix_order_disputes_status_created_at
    on order_disputes (status, created_at desc);

create index if not exists ix_order_disputes_assigned_support_user_id
    on order_disputes (assigned_support_user_id, created_at desc);

create index if not exists ix_order_disputes_created_at
    on order_disputes (created_at desc);

create unique index if not exists ux_order_disputes_order_active
    on order_disputes (order_id)
    where status in ('open', 'in_review');

create trigger trg_order_disputes_touch_updated_at
    before update on order_disputes
    for each row
execute function touch_updated_at();

alter table order_events
    drop constraint if exists order_events_event_type_check;

alter table order_events
    add constraint order_events_event_type_check
        check (
            event_type in (
                'order_created',
                'maker_confirmed_ready',
                'order_canceled',
                'order_expired',
                'seller_marked_partial_delivery',
                'seller_marked_delivered',
                'buyer_confirmed_received',
                'order_completed',
                'change_requested',
                'change_approved',
                'change_rejected',
                'cancel_requested',
                'cancel_request_approved',
                'cancel_request_rejected',
                'amend_quantity_requested',
                'amend_quantity_approved',
                'amend_quantity_rejected',
                'dispute_opened',
                'dispute_taken_in_work',
                'dispute_resolved',
                'order_force_canceled_by_support',
                'order_force_completed_by_support',
                'order_force_amended_quantity_by_support'
            )
        );

alter table order_events
    drop constraint if exists order_events_actor_role_check;

alter table order_events
    add constraint order_events_actor_role_check
        check (
            actor_role is null
                or actor_role in ('buyer', 'seller', 'support', 'system')
        );

alter table order_events
    drop constraint if exists order_events_actor_fields_check;

alter table order_events
    add constraint order_events_actor_fields_check
        check (
            (actor_role is null and actor_user_id is null)
                or (actor_role in ('buyer', 'seller', 'support') and actor_user_id is not null)
                or (actor_role = 'system' and actor_user_id is null)
        );

insert into permissions (code)
select v.code
from (values
          ('ORDERS_VIEW_ANY'),
          ('ORDER_DISPUTES_VIEW'),
          ('ORDER_DISPUTES_CREATE'),
          ('ORDER_DISPUTES_TAKE'),
          ('ORDER_DISPUTES_RESOLVE'),
          ('ORDER_CHATS_VIEW_ANY'),
          ('ORDER_CHATS_SEND_AS_SUPPORT')) as v(code)
where not exists(select 1
                 from permissions p
                 where lower(p.code) = lower(v.code));
