create table if not exists email_verification_tokens
(
    id           bigint primary key generated by default as identity,
    user_id      bigint      not null references users (id) on delete cascade,
    token_hash   varchar(64) not null,
    expires_at   timestamptz not null,
    confirmed_at timestamptz,

    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);

create unique index if not exists ux_email_verification_tokens_token_hash
    on email_verification_tokens (token_hash);

create index if not exists ix_email_verification_tokens_user_id
    on email_verification_tokens (user_id);
