create extension if not exists pgcrypto;

alter table deposit_requests
    add column currency_code_snapshot varchar(16),
    add column deposit_method_title_snapshot text;

update deposit_requests dr
set currency_code_snapshot = dm.currency_code,
    deposit_method_title_snapshot = coalesce(dm.title, '')
from deposit_methods dm
where dr.deposit_method_id = dm.id
  and (dr.currency_code_snapshot is null or dr.deposit_method_title_snapshot is null);

alter table deposit_requests
    alter column currency_code_snapshot set not null,
    alter column deposit_method_title_snapshot set not null;

create index if not exists idx_deposit_requests_user_status_created_at
    on deposit_requests (user_id, status, created_at desc);

create index if not exists idx_deposit_requests_status_created_at
    on deposit_requests (status, created_at desc);

create table withdrawal_methods
(
    id                bigint primary key generated by default as identity,
    code              varchar(64)    not null,
    title             text           not null,
    currency_code     varchar(16)    not null references currencies (code),
    requisites_schema jsonb          not null default '{}'::jsonb,
    min_amount        decimal(13, 4),
    is_active         boolean        not null default true,
    note              text,
    created_at        timestamptz    not null default now(),
    updated_at        timestamptz    not null default now(),

    constraint uq_withdrawal_methods_code_currency
        unique (code, currency_code),

    constraint ck_withdrawal_methods_min_amount_positive
        check (min_amount is null or min_amount > 0)
);

create index if not exists idx_withdrawal_methods_currency_active
    on withdrawal_methods (currency_code, is_active, id);

create trigger trg_withdrawal_methods_touch_updated_at
    before update on withdrawal_methods
    for each row
execute function touch_updated_at();

create table payout_profiles
(
    id                   bigint primary key generated by default as identity,
    public_id            uuid        not null default gen_random_uuid(),
    user_id              bigint      not null references users (id) on delete cascade,
    withdrawal_method_id bigint      not null references withdrawal_methods (id),
    title                text        not null,
    requisites           jsonb       not null,
    is_default           boolean     not null default false,
    is_active            boolean     not null default true,
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now()
);

create unique index if not exists uq_payout_profiles_public_id
    on payout_profiles (public_id);

create index if not exists idx_payout_profiles_user_active_created_at
    on payout_profiles (user_id, is_active, created_at desc);

create index if not exists idx_payout_profiles_user_method_active
    on payout_profiles (user_id, withdrawal_method_id, is_active, created_at desc);

create unique index if not exists uq_payout_profiles_user_method_default_active
    on payout_profiles (user_id, withdrawal_method_id)
    where is_default = true and is_active = true;

create trigger trg_payout_profiles_touch_updated_at
    before update on payout_profiles
    for each row
execute function touch_updated_at();

create type withdrawal_request_status as enum (
    'OPEN',
    'PROCESSING',
    'COMPLETED',
    'CANCELLED',
    'REJECTED'
    );

create table withdrawal_requests
(
    id                             bigint primary key generated by default as identity,
    public_id                      uuid                    not null default gen_random_uuid(),
    user_id                        bigint                  not null references users (id) on delete cascade,
    user_account_id                bigint                  not null references user_accounts (id),
    currency_code_snapshot         varchar(16)             not null,
    withdrawal_method_id           bigint                  not null references withdrawal_methods (id),
    withdrawal_method_code_snapshot varchar(64)            not null,
    withdrawal_method_title_snapshot text                  not null,
    payout_profile_id              bigint references payout_profiles (id),
    requisites_snapshot            jsonb                   not null,
    amount                         decimal(13, 4)          not null,
    actual_payout_amount           decimal(13, 4),
    status                         withdrawal_request_status not null default 'OPEN',
    method_note_snapshot           text,
    operator_comment               text,
    rejection_reason               text,
    opened_at                      timestamptz             not null default now(),
    processing_at                  timestamptz,
    completed_at                   timestamptz,
    cancelled_at                   timestamptz,
    rejected_at                    timestamptz,
    processed_by_user_id           bigint references users (id),
    created_at                     timestamptz             not null default now(),
    updated_at                     timestamptz             not null default now(),

    constraint ck_withdrawal_requests_amount_positive
        check (amount > 0),

    constraint ck_withdrawal_requests_actual_amount_positive
        check (actual_payout_amount is null or actual_payout_amount > 0)
);

create unique index if not exists uq_withdrawal_requests_public_id
    on withdrawal_requests (public_id);

create index if not exists idx_withdrawal_requests_user_created_at
    on withdrawal_requests (user_id, created_at desc);

create index if not exists idx_withdrawal_requests_user_status_created_at
    on withdrawal_requests (user_id, status, created_at desc);

create index if not exists idx_withdrawal_requests_status_created_at
    on withdrawal_requests (status, created_at desc);

create index if not exists idx_withdrawal_requests_processed_by_status
    on withdrawal_requests (processed_by_user_id, status, created_at desc);

create index if not exists idx_withdrawal_requests_user_account
    on withdrawal_requests (user_account_id);

create trigger trg_withdrawal_requests_touch_updated_at
    before update on withdrawal_requests
    for each row
execute function touch_updated_at();

insert into permissions (code)
select v.code
from (values
          ('WITHDRAWAL_REQUESTS_VIEW'),
          ('WITHDRAWAL_REQUESTS_TAKE'),
          ('WITHDRAWAL_REQUESTS_REJECT'),
          ('WITHDRAWAL_REQUESTS_CONFIRM')) as v(code)
where not exists(select 1
                 from permissions p
                 where lower(p.code) = lower(v.code));
