create table notifications
(
    id         bigint primary key generated by default as identity,
    public_id  uuid         not null,
    user_id    bigint       not null references users (id) on delete cascade,
    type       varchar(64)  not null,
    title      varchar(200) not null,
    body       text         not null,
    payload    jsonb        not null default '{}'::jsonb,
    is_read    boolean      not null default false,
    created_at timestamptz  not null default now(),
    read_at    timestamptz  null,

    constraint ux_notifications_public_id
        unique (public_id),

    constraint notifications_type_check
        check (
            type in (
                'order_created',
                'order_status_changed',
                'order_message_received',
                'order_request_created',
                'order_request_resolved',
                'dispute_opened',
                'dispute_taken_in_work',
                'deposit_confirmed',
                'deposit_rejected',
                'withdrawal_completed',
                'withdrawal_rejected'
            )
        ),

    constraint notifications_title_not_blank
        check (btrim(title) <> ''),

    constraint notifications_body_not_blank
        check (btrim(body) <> ''),

    constraint notifications_payload_object
        check (jsonb_typeof(payload) = 'object'),

    constraint notifications_read_state_check
        check (
            (is_read = false and read_at is null)
                or (is_read = true and read_at is not null)
        )
);

create index if not exists ix_notifications_user_created_at
    on notifications (user_id, created_at desc);

create index if not exists ix_notifications_user_is_read
    on notifications (user_id, is_read);
