create table money_operation_events
(
    id                  bigint primary key generated by default as identity,
    operation_type      varchar(64) not null,
    operation_id        bigint      not null,
    operation_code      varchar(16) not null,
    event_type          varchar(96) not null,
    status_before       varchar(64),
    status_after        varchar(64),
    actor_type          varchar(32) not null,
    actor_user_id       bigint references users (id) on delete set null,
    public_note         text,
    operator_note       text,
    payload             jsonb       not null default '{}'::jsonb,
    created_at          timestamptz not null default now(),

    constraint ck_money_operation_events_operation_type
        check (operation_type in ('DEPOSIT_REQUEST', 'WITHDRAWAL_REQUEST')),

    constraint ck_money_operation_events_actor_type
        check (actor_type in ('USER', 'OPERATOR', 'SYSTEM'))
);

create index idx_money_operation_events_operation_created_at
    on money_operation_events (operation_type, operation_code, created_at, id);

create index idx_money_operation_events_actor_created_at
    on money_operation_events (actor_user_id, created_at desc)
    where actor_user_id is not null;

alter table deposit_requests
    add column details_issued_by_user_id bigint references users (id) on delete set null,
    add column confirmed_by_user_id bigint references users (id) on delete set null,
    add column rejected_by_user_id bigint references users (id) on delete set null,
    add column confirmation_reference text,
    add column operator_comment text;
