create table treasury_accounts
(
    id            bigint primary key generated by default as identity,
    code          varchar(64)    not null,
    title         text           not null,
    currency_code varchar(16)    not null references currencies (code),
    account_type  varchar(32)    not null,
    balance       decimal(19, 4) not null default 0,
    is_active     boolean        not null default true,
    details       jsonb          not null default '{}'::jsonb,
    note          text,
    created_at    timestamptz    not null default now(),
    updated_at    timestamptz    not null default now(),

    constraint uq_treasury_accounts_code unique (code),
    constraint ck_treasury_accounts_type
        check (account_type in (
            'BANK_CARD',
            'BANK_ACCOUNT',
            'CRYPTO_WALLET',
            'EXCHANGE_ACCOUNT',
            'P2P_DROP',
            'CASH',
            'OTHER'
        ))
);

create index idx_treasury_accounts_currency_active
    on treasury_accounts (currency_code, is_active, title);

create trigger trg_treasury_accounts_touch_updated_at
    before update on treasury_accounts
    for each row
execute function touch_updated_at();

create table treasury_transactions
(
    id                    bigint primary key generated by default as identity,
    group_key             varchar(64),
    treasury_account_id   bigint         not null references treasury_accounts (id),
    amount                decimal(19, 4) not null,
    transaction_type      varchar(64)    not null,
    operation_type        varchar(64),
    operation_id          bigint,
    operation_code        varchar(16),
    external_reference    text,
    description           text,
    operator_comment      text,
    actor_user_id         bigint references users (id) on delete set null,
    metadata              jsonb          not null default '{}'::jsonb,
    created_at            timestamptz    not null default now(),

    constraint ck_treasury_transactions_amount_nonzero check (amount <> 0),
    constraint ck_treasury_transactions_type
        check (transaction_type in (
            'DEPOSIT_IN',
            'WITHDRAWAL_OUT',
            'MANUAL_IN',
            'MANUAL_OUT',
            'ADJUSTMENT',
            'TRANSFER_IN',
            'TRANSFER_OUT'
        )),
    constraint ck_treasury_transactions_operation_type
        check (operation_type is null or operation_type in ('DEPOSIT_REQUEST', 'WITHDRAWAL_REQUEST'))
);

create index idx_treasury_transactions_account_created_at
    on treasury_transactions (treasury_account_id, created_at desc, id desc);

create index idx_treasury_transactions_operation
    on treasury_transactions (operation_type, operation_code, created_at desc)
    where operation_type is not null and operation_code is not null;

create index idx_treasury_transactions_actor_created_at
    on treasury_transactions (actor_user_id, created_at desc)
    where actor_user_id is not null;

create or replace function fn_treasury_transactions_apply_balance()
    returns trigger
    language plpgsql
as $$
begin
    update treasury_accounts
    set balance = balance + new.amount
    where id = new.treasury_account_id;

    return new;
end;
$$;

create trigger trg_treasury_transactions_apply_balance
    after insert on treasury_transactions
    for each row
execute function fn_treasury_transactions_apply_balance();

create or replace function fn_treasury_transactions_block_mutation()
    returns trigger
    language plpgsql
as $$
begin
    if tg_op = 'UPDATE' then
        if new.id <> old.id
            or new.group_key is distinct from old.group_key
            or new.treasury_account_id <> old.treasury_account_id
            or new.amount <> old.amount then
            raise exception 'Updating immutable treasury transaction fields is not allowed';
        end if;

        return new;
    end if;

    if tg_op = 'DELETE' then
        raise exception 'Deleting rows from treasury_transactions is not allowed';
    end if;

    return null;
end;
$$;

create trigger trg_treasury_transactions_block_update
    before update on treasury_transactions
    for each row
execute function fn_treasury_transactions_block_mutation();

create trigger trg_treasury_transactions_block_delete
    before delete on treasury_transactions
    for each row
execute function fn_treasury_transactions_block_mutation();

alter table deposit_requests
    add column treasury_account_id bigint references treasury_accounts (id) on delete set null,
    add column treasury_transaction_id bigint references treasury_transactions (id) on delete set null;

alter table withdrawal_requests
    add column treasury_account_id bigint references treasury_accounts (id) on delete set null,
    add column treasury_transaction_id bigint references treasury_transactions (id) on delete set null;

insert into permissions (code)
select v.code
from (values
          ('TREASURY_VIEW'),
          ('TREASURY_MANAGE')) as v(code)
where not exists(select 1
                 from permissions p
                 where lower(p.code) = lower(v.code));
