create table deposit_payment_routes
(
    id                  bigint primary key generated by default as identity,
    deposit_method_id   bigint         not null references deposit_methods (id) on delete cascade,
    treasury_account_id bigint         not null references treasury_accounts (id) on delete restrict,
    title               text           not null,
    payment_details     jsonb          not null default '{}'::jsonb,
    min_amount          decimal(13, 4),
    max_amount          decimal(13, 4),
    priority            int            not null default 100,
    is_active           boolean        not null default true,
    note                text,
    created_at          timestamptz    not null default now(),
    updated_at          timestamptz    not null default now(),

    constraint ck_deposit_payment_routes_min_positive check (min_amount is null or min_amount > 0),
    constraint ck_deposit_payment_routes_max_positive check (max_amount is null or max_amount > 0),
    constraint ck_deposit_payment_routes_min_lte_max
        check (min_amount is null or max_amount is null or min_amount <= max_amount)
);

create index idx_deposit_payment_routes_method_active_priority
    on deposit_payment_routes (deposit_method_id, is_active, priority, id);

create index idx_deposit_payment_routes_treasury_account
    on deposit_payment_routes (treasury_account_id);

create trigger trg_deposit_payment_routes_touch_updated_at
    before update on deposit_payment_routes
    for each row
execute function touch_updated_at();

create table deposit_payment_instructions
(
    id                              bigint primary key generated by default as identity,
    deposit_request_id              bigint         not null references deposit_requests (id) on delete cascade,
    deposit_payment_route_id        bigint references deposit_payment_routes (id) on delete set null,
    treasury_account_id             bigint references treasury_accounts (id) on delete set null,
    payment_details_snapshot        jsonb          not null default '{}'::jsonb,
    amount                          decimal(13, 4) not null,
    currency_code_snapshot          varchar(16)    not null references currencies (code),
    treasury_amount                 decimal(19, 4),
    treasury_currency_code_snapshot varchar(16) references currencies (code),
    status                          varchar(32)    not null default 'ACTIVE',
    expires_at                      timestamptz,
    issued_at                       timestamptz    not null default now(),
    issued_by_user_id               bigint references users (id) on delete set null,
    operator_comment                text,

    constraint uq_deposit_payment_instructions_request unique (deposit_request_id),
    constraint ck_deposit_payment_instructions_amount_positive check (amount > 0),
    constraint ck_deposit_payment_instructions_treasury_amount_positive
        check (treasury_amount is null or treasury_amount > 0),
    constraint ck_deposit_payment_instructions_status
        check (status in ('ACTIVE', 'USED', 'CANCELLED'))
);

create index idx_deposit_payment_instructions_route
    on deposit_payment_instructions (deposit_payment_route_id);

create index idx_deposit_payment_instructions_treasury_account
    on deposit_payment_instructions (treasury_account_id);

alter table deposit_requests
    add column payment_instruction_id bigint references deposit_payment_instructions (id) on delete set null;

create table withdrawal_payout_plans
(
    id                              bigint primary key generated by default as identity,
    withdrawal_request_id           bigint         not null references withdrawal_requests (id) on delete cascade,
    treasury_account_id             bigint         not null references treasury_accounts (id) on delete restrict,
    planned_user_amount             decimal(13, 4) not null,
    user_currency_code_snapshot     varchar(16)    not null references currencies (code),
    treasury_amount                 decimal(19, 4) not null,
    treasury_currency_code_snapshot varchar(16)    not null references currencies (code),
    external_reference              text,
    operator_comment                text,
    status                          varchar(32)    not null default 'PLANNED',
    planned_by_user_id              bigint references users (id) on delete set null,
    planned_at                      timestamptz    not null default now(),
    completed_at                    timestamptz,
    cancelled_at                    timestamptz,

    constraint uq_withdrawal_payout_plans_request unique (withdrawal_request_id),
    constraint ck_withdrawal_payout_plans_user_amount_positive check (planned_user_amount > 0),
    constraint ck_withdrawal_payout_plans_treasury_amount_positive check (treasury_amount > 0),
    constraint ck_withdrawal_payout_plans_status
        check (status in ('PLANNED', 'COMPLETED', 'CANCELLED'))
);

create index idx_withdrawal_payout_plans_treasury_account
    on withdrawal_payout_plans (treasury_account_id);

alter table withdrawal_requests
    add column payout_plan_id bigint references withdrawal_payout_plans (id) on delete set null;

alter table platform_accounts
    add column account_code varchar(64),
    add column title text,
    add column is_active boolean not null default true,
    add column note text,
    add column created_at timestamptz not null default now(),
    add column updated_at timestamptz not null default now();

alter table platform_accounts
    alter column currency_code type varchar(16),
    alter column balance type decimal(19, 4),
    alter column reserved type decimal(19, 4);

update platform_accounts
set account_code = 'FEES',
    title = 'Platform fees ' || currency_code
where account_code is null;

alter table platform_accounts
    alter column account_code set not null,
    alter column title set not null,
    drop constraint if exists uq_platform_accounts_currency_code,
    drop constraint if exists ck_platform_accounts_balance_nonnegative,
    drop constraint if exists ck_platform_accounts_balance_ge_reserved,
    add constraint uq_platform_accounts_code_currency unique (account_code, currency_code),
    add constraint ck_platform_accounts_code
        check (account_code in ('FX_DESK', 'FEES', 'ROUNDING', 'ADJUSTMENTS', 'EQUITY'));

create index idx_platform_accounts_currency_active
    on platform_accounts (currency_code, is_active, account_code);

create trigger trg_platform_accounts_touch_updated_at
    before update on platform_accounts
    for each row
execute function touch_updated_at();

create table platform_account_transactions
(
    id                  bigint primary key generated by default as identity,
    group_key           varchar(64),
    platform_account_id bigint         not null references platform_accounts (id),
    amount              decimal(19, 4) not null,
    transaction_type    varchar(64)    not null,
    ref_type            varchar(64),
    ref_id              bigint,
    ref_code            varchar(32),
    description         text,
    actor_user_id       bigint references users (id) on delete set null,
    metadata            jsonb          not null default '{}'::jsonb,
    created_at          timestamptz    not null default now(),

    constraint ck_platform_account_transactions_amount_nonzero check (amount <> 0),
    constraint ck_platform_account_transactions_type
        check (transaction_type in ('FX_IN', 'FX_OUT', 'FEE', 'ROUNDING', 'ADJUSTMENT', 'MANUAL'))
);

create index idx_platform_account_transactions_account_created_at
    on platform_account_transactions (platform_account_id, created_at desc, id desc);

create index idx_platform_account_transactions_ref
    on platform_account_transactions (ref_type, ref_code, created_at desc)
    where ref_type is not null and ref_code is not null;

create or replace function fn_platform_account_transactions_apply_balance()
    returns trigger
    language plpgsql
as $$
begin
    update platform_accounts
    set balance = balance + new.amount
    where id = new.platform_account_id;

    return new;
end;
$$;

create trigger trg_platform_account_transactions_apply_balance
    after insert on platform_account_transactions
    for each row
execute function fn_platform_account_transactions_apply_balance();

create or replace function fn_platform_account_transactions_block_mutation()
    returns trigger
    language plpgsql
as $$
begin
    if tg_op = 'UPDATE' then
        if new.id <> old.id
            or new.group_key is distinct from old.group_key
            or new.platform_account_id <> old.platform_account_id
            or new.amount <> old.amount then
            raise exception 'Updating immutable platform transaction fields is not allowed';
        end if;

        return new;
    end if;

    if tg_op = 'DELETE' then
        raise exception 'Deleting rows from platform_account_transactions is not allowed';
    end if;

    return null;
end;
$$;

create trigger trg_platform_account_transactions_block_update
    before update on platform_account_transactions
    for each row
execute function fn_platform_account_transactions_block_mutation();

create trigger trg_platform_account_transactions_block_delete
    before delete on platform_account_transactions
    for each row
execute function fn_platform_account_transactions_block_mutation();

create table user_currency_conversions
(
    id                  bigint primary key generated by default as identity,
    public_code         varchar(16)    not null default generate_public_code('CNV'),
    user_id             bigint         not null references users (id) on delete cascade,
    from_account_id     bigint         not null references user_accounts (id),
    to_account_id       bigint         not null references user_accounts (id),
    from_currency_code  varchar(16)    not null references currencies (code),
    to_currency_code    varchar(16)    not null references currencies (code),
    from_amount         decimal(13, 4) not null,
    to_amount           decimal(13, 4) not null,
    rate                decimal(20, 8) not null,
    rate_source         varchar(32)    not null,
    status              varchar(32)    not null default 'COMPLETED',
    created_at          timestamptz    not null default now(),

    constraint uq_user_currency_conversions_public_code unique (public_code),
    constraint ck_user_currency_conversions_amounts_positive
        check (from_amount > 0 and to_amount > 0),
    constraint ck_user_currency_conversions_rate_positive check (rate > 0),
    constraint ck_user_currency_conversions_different_currencies
        check (from_currency_code <> to_currency_code),
    constraint ck_user_currency_conversions_status check (status in ('COMPLETED'))
);

create index idx_user_currency_conversions_user_created_at
    on user_currency_conversions (user_id, created_at desc, id desc);

drop index if exists ux_user_account_txs_ref;

create unique index if not exists ux_user_account_txs_ref_type
    on user_account_txs (ref_type, ref_id, type);

insert into permissions (code)
select v.code
from (values
          ('PLATFORM_ACCOUNTS_VIEW'),
          ('PLATFORM_ACCOUNTS_MANAGE')) as v(code)
where not exists(select 1
                 from permissions p
                 where lower(p.code) = lower(v.code));
