create table user_accounts (
    id bigint PRIMARY KEY generated by default as identity,
    user_id bigint not null references users(id),
    currency_code varchar(5) not null references currencies(code),
    balance decimal(13,4) not null,
    reserved decimal(13,4) not null,

    constraint ck_user_accounts_balance_nonnegative check (balance >= 0),
    constraint ck_user_accounts_reserved_nonnegative check (reserved >= 0),
    constraint ck_user_accounts_balance_ge_reserved check (balance >= reserved),
    -- У каждого пользователя может быть только один кошелек в какой-либо валюте
    constraint uq_user_accounts_user_currency unique (user_id, currency_code)
)
