create table if not exists password_change_tokens
(
    id                bigint primary key generated by default as identity,
    user_id           bigint      not null references users (id) on delete cascade,
    token_hash        varchar(64) not null,
    new_password_hash varchar(255) not null,
    expires_at        timestamptz not null,
    confirmed_at      timestamptz,

    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

create unique index if not exists ux_password_change_tokens_token_hash
    on password_change_tokens (token_hash);

create index if not exists ix_password_change_tokens_user_id
    on password_change_tokens (user_id);
