create table deposit_methods
(
    id                bigint primary key generated by default as identity,
    title text,
    currency_code varchar(16) not null references currencies(code),
    payment_details jsonb,
    auto_confirmation boolean default false,
    is_active boolean default true
);
